### ISSUE TITLE
Html.ImageGetter

### ISSUE THREAD

**Issue by Borales** [nostra13/Android-Universal-Image-Loader#451]
Hi! Thanks for your library!
I have a small question. Is there a way to set UIL as loader for Html.ImageGetter?
I can't figure out how to mix them.

**Comment by ozuf** [comment]
How can one listen for clicks on the displayed images?

**Comment by MuhammadAbrarx** [comment]
use onClickListener if imageView .. otherwise for Gridview etc use onItemClickListener .. google for how to implement them .. but if u are using a threading system to Display images directly using imageLoader.display ... then u got a different case , and far more explanations needed for that situation ..  plz mention which is your case ..

**Comment by ozuf** [comment]
Ok, this is how I'm using it: I fetch and parse html from the web using jsoup. The parsed text contains img tags in random positions in the text. I load these images using user Borales's UilImageGetter.

So the images doesn't have ImageView and I'm using imageLoader.display ... .
