### ISSUE TITLE
Verify remote image changed ETag/If-Modified-Since

### ISSUE THREAD

**Issue by moisesvs** [nostra13/Android-Universal-Image-Loader#492]
Hello!

In this post: https://github.com/nostra13/Android-Universal-Image-Loader/issues/75 you said that you could check if the etag has been modified and delete the picture or not. The problem is that this method is called when a new connection is opened. If you want to always check if the image has been modified to show the one in the cache and if a new update has taIked modification. How could we?

Thanks!

**Comment by sergiiz** [comment]
Hi, are there any updates about this issue?

**Comment by paulito415** [comment]
Hi, looking for updates on this issue too. From the documentation it's not entirely clear what your cache expiration policy is and if we're getting image resources from a URL it is almost always better if we can follow HTTP Caching specifications than if you had your own custom logic to determine expiration, for obvious reasons - i.e. if the image has expired but the Android client still loads the old version from the cache, it is technically wrong.

I agree with the points raised above about the life-cycle of the requests by moisesvs (as in, the first try should be using If-Modified-Since or If-None-Match because only that will return the 304 and let you know that your cache is still valid). It should not be "intercepted" later in getStream where it already went through a cache expiration logic of your own. 

What I think we're suggesting is maybe having the ability to override the logic which calls getStream (a quick search of where it's called found BrokenJpegImageDecoder, BaseImageDecoder, LoadAndDisplayImageTask.downloadImage and NetworkDeniedImageDownloader). I have a feeling that the appropriate place is probably LoadAndDisplayImageTask. But it is declared a final class - no way to extend it. Is there a future version of this that can allow us to modify the logic I was speaking to earlier?

Thanks,
Paul
