### ISSUE TITLE
Load multi image offline error

### ISSUE THREAD

**Issue by NhamPhanDinh** [nostra13/Android-Universal-Image-Loader#548]
Hi, 
I am using universal image loader it working fine.

I load images into one HorizontalScrollView. There are about 100 photos, different sizes, medium heavy 500KB per image. There are some pictures up to 2000px width. 
When I scroll the image, a normal image display with your library. However, when the memory is full, the next image display size is 2000px, the library will decode the image to a much smaller size and scale it up convertView. So the image is not displayed properly and blur. 
What I want is to see such case, we will free up memory and display the image correctly

**Comment by YarivZghoul** [comment]
HI ,
I am using universal image loader in my application .I'm also load the images in HorizontalScrollView and this HorizontalScrollView  as row in ListView per item .Images are load and working fine with re-size  the images .There are about 1000 of and above images .But the problem is when i scroll the ListView at first time its fine but after scrolling spacing between ImageViews added to HorizontalScrollView increases.How to solve this issue.
