### ISSUE TITLE
Problem with recyclerview and StaggeredGridLayoutManager

### ISSUE THREAD

**Issue by RaffiOhanian** [nostra13/Android-Universal-Image-Loader#816]
HI Guys 

Im having problems when trying to use the universalImageDownloader with StaggeredGridLayoutManager and recycler view. after the images are loaded the positions are being changed for the children of the StaggeredGridLayoutManager, I know its from the downloader because i tried the same thing without using the downloader and the problem went away. 

The problem is that somehow im getting gaps in the StaggeredGridLayoutManager and its trying to fill the gaps which is causeing my images to move around suddenly . 

Can you suggest anything for this ?

regards

**Comment by naman14** [comment]
@RaffiOhanian can you please elaborate how you fixed the problem? I am having the same problem.

**Comment by RaffiOhanian** [comment]
You should use RecyclerView's item decoration.
https://developer.android.com/reference/android/support/v7/widget/RecyclerView.ItemDecoration.html

**Comment by VihaanVerma89** [comment]
I have a similar implementation and in my case the images shuffle after it gets loaded. One reasons I can think of such behavior is that the image sizes are different with some being square and some being rectangle with height being greater. Possible solution might be know the aspect ration of images getting loaded beforehand thus defining the dimension of the image view, otherwise it would cause the shuffle.

**Comment by AmitaInsan** [comment]
I am using the UIL but images are shuffling. I have created a signle instance of imageloader in adpapter then also images are shuffling.
